site_name: DEVPORTAL

plugins:
  - search
  - swagger-ui-tag
  - mkdocstrings
  - tags
  - mermaid2
  - git-revision-date-localized:
      locale: pt_BR
      type: datetime
      fallback_to_build_date: false
      enable_creation_date: true 


theme:
  name: material
  palette:
  primary: custom
  accent: custom
  language: pt-BR
  # logo: assets/logo.png
extra_css:
  - css/custom.css