openapi: 3.0.0
info:
  title: API de Tarefas (To-Do)
  description: API para gerenciar tarefas diárias
  version: 1.0.0
  contact:
    email: dev@example.com

servers:
  - url: https://api.example.com/v1
    description: Servidor de Produção

paths:
  /tasks:
    get:
      summary: Listar todas as tarefas
      responses:
        200:
          description: Lista de tarefas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    
    post:
      summary: Criar uma nova tarefa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        201:
          description: Tarefa criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      summary: Buscar tarefa por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Tarefa encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        404:
          description: Tarefa não encontrada
    
    delete:
      summary: Excluir tarefa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Tarefa excluída com sucesso

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Comprar leite
        completed:
          type: boolean
          example: false
    
    TaskInput:
      type: object
      properties:
        title:
          type: string
          example: Ler documentação do Swagger
        completed:
          type: boolean
          example: false
      required:
        - title